### ISSUE TITLE
ReduceOps Couldn't be decompiled

### ISSUE THREAD

**Issue by Thihup** [QuiltMC/quiltflower#125]
File: https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/stream/ReduceOps.java

```java
public static TerminalOp<Integer, Integer> makeInt(final int identity, final IntBinaryOperator operator) {
    Objects.requireNonNull(operator);
    return new ReduceOps.ReduceOp<Integer, Integer, ReducingSink>(StreamShape.INT_VALUE) {
      public ReducingSink makeSink() {
        // $FF: Couldn't be decompiled
        // Please report this to the Quiltflower issue tracker, at https://github.com/QuiltMC/quiltflower/issues with a copy of the class file (if you have the rights to distribute it!)
        // java.lang.IndexOutOfBoundsException: Index: 0
        //   at java.base/java.util.Collections$EmptyList.get(Collections.java:4483)
        //   at org.jetbrains.java.decompiler.modules.decompiler.exps.InvocationExprent.getInferredExprType(InvocationExprent.java:365)
        //   at org.jetbrains.java.decompiler.modules.decompiler.exps.InvocationExprent.appendParamList(InvocationExprent.java:901)
        //   at org.jetbrains.java.decompiler.modules.decompiler.exps.NewExprent.toJava(NewExprent.java:453)
        //   at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.getCastedExprent(ExprProcessor.java:974)
        //   at org.jetbrains.java.decompiler.modules.decompiler.exps.ExitExprent.toJava(ExitExprent.java:82)
        //   at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.listToJava(ExprProcessor.java:858)
        //   at org.jetbrains.java.decompiler.modules.decompiler.stats.BasicBlockStatement.toJava(BasicBlockStatement.java:65)
        //   at org.jetbrains.java.decompiler.modules.decompiler.stats.RootStatement.toJava(RootStatement.java:37)
        //   at org.jetbrains.java.decompiler.main.ClassWriter.methodToJava(ClassWriter.java:1084)
        //
        // Bytecode:
        // 0: new java/util/stream/ReduceOps$5ReducingSink
        // 3: dup
        // 4: aload 0
        // 5: getfield java/util/stream/ReduceOps$6.val$identity I
        // 8: aload 0
        // 9: getfield java/util/stream/ReduceOps$6.val$operator Ljava/util/function/IntBinaryOperator;
        // c: invokespecial java/util/stream/ReduceOps$5ReducingSink.<init> (ILjava/util/function/IntBinaryOperator;)V
        // f: areturn
      }
    };

    class ReducingSink implements ReduceOps.AccumulatingSink<Integer, Integer, ReducingSink>, java.util.stream.Sink.OfInt {
      private int state;

      ReducingSink(IntBinaryOperator var2) {
        this.val$operator = var2;
      }

      public void begin(long size) {
        this.state = (int)ReduceOps.this;
      }

      public void accept(int t) {
        this.state = this.val$operator.applyAsInt(this.state, t);
      }

      public Integer get() {
        return this.state;
      }

      public void combine(ReducingSink other) {
        this.accept(other.state);
      }
    }

  }
```

**Comment by SuperCoder7979** [comment]
Fixed by 14af99af. Thanks so much for the report!
