### ISSUE TITLE
Random NPEs while decompiling

### ISSUE THREAD

**Issue by ByMartrixx** [QuiltMC/quiltflower#13]
Here are some of the stacktraces
[`Cannot read field "nested" because "parent_class" is null`](https://hastebin.com/usatexujeq)
[Three in a row](https://hastebin.com/eboqifulaz)

I haven't managed to reproduce any of these
I was using Quiltflower 1.4.1 with fabric-loom 0.7 with this
```gradle
buildscript {
    repositories {
        mavenCentral()
        maven {
            name 'Fabric'
            url 'https://maven.fabricmc.net/'
        }
        mavenLocal()
    }
    dependencies {
        classpath (group: 'fabric-loom', name: 'fabric-loom.gradle.plugin', version: '0.7-SNAPSHOT') { // From Fabric
            exclude group: 'net.fabricmc', module: 'fabric-fernflower'
        }
        classpath 'org.quiltmc:quiltflower:1.4.1+local' // From mavenLocal
    }
}
```

**Comment by ByMartrixx** [comment]
Just got a different one while decompiling pre4
```
Class net/minecraft/world/gen/feature/size/ThreeLayersFeatureSize couldn't be fully decompiled.
java.lang.NullPointerException: Cannot read field "anonymousClassType" because the return value of "java.util.Map.get(Object)" is null
at org.jetbrains.java.decompiler.modules.decompiler.exps.NewExprent.getExprType(NewExprent.java:90)
at org.jetbrains.java.decompiler.modules.decompiler.exps.NewExprent.getInferredExprType(NewExprent.java:252)
at org.jetbrains.java.decompiler.modules.decompiler.exps.InvocationExprent.getInferredExprType(InvocationExprent.java:361)
at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.getCastedExprent(ExprProcessor.java:914)
at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.getCastedExprent(ExprProcessor.java:887)
at org.jetbrains.java.decompiler.main.ClassWriter.fieldToJava(ClassWriter.java:646)
at org.jetbrains.java.decompiler.main.ClassWriter.classToJava(ClassWriter.java:258)
at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:406)
at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:146)
at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$0(ContextUnit.java:170)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by ByMartrixx** [comment]
[More in a row](https://hastebin.com/ugabogopuv) when reattempting to decompile pre4. No new ones this time

**Comment by ByMartrixx** [comment]
New one
```
Class net/minecraft/class_6402 couldn't be fully decompiled.
java.lang.NullPointerException: Cannot invoke "org.jetbrains.java.decompiler.modules.decompiler.sforms.DirectGraph.iterateExprents(org.jetbrains.java.decompiler.modules.decompiler.sforms.DirectGraph$ExprentIterator)" because the return value of "org.jetbrains.java.decompiler.main.rels.MethodWrapper.getOrBuildGraph()" is null
at org.jetbrains.java.decompiler.main.rels.NestedClassProcessor.setLambdaVars(NestedClassProcessor.java:242)
at org.jetbrains.java.decompiler.main.rels.NestedClassProcessor.processClass(NestedClassProcessor.java:76)
at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:401)
at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:146)
at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$0(ContextUnit.java:170)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by SuperCoder7979** [comment]
Should be fixed. Please re-open the issue if you run into similar issues
