### ISSUE TITLE
 Zip END header not found

### ISSUE THREAD

**Issue by vipreshjha** [QuiltMC/quiltflower#176]
While trying to decompile a jar file, getting this error

INFO:  JVM info: Oracle Corporation - 1.8.0_331 - 25.331-b09
INFO:  Adding Archive: c:\rox-server-decom\rox-server-core-1.0-SNAPSHOT.jar
Exception in thread "main" java.util.zip.ZipError: zip END header not found
        at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1643)
        at com.sun.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1021)
        at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1030)
        at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130)
        at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
        at java.nio.file.FileSystems.newFileSystem(Unknown Source)
        at java.nio.file.FileSystems.newFileSystem(Unknown Source)
        at org.jetbrains.java.decompiler.struct.StructContext.addArchive(StructContext.java:149)
        at org.jetbrains.java.decompiler.struct.StructContext.addSpace(StructContext.java:112)
        at org.jetbrains.java.decompiler.struct.StructContext.addSpace(StructContext.java:101)
        at org.jetbrains.java.decompiler.struct.StructContext.addSpace(StructContext.java:74)
        at org.jetbrains.java.decompiler.main.Fernflower.addSource(Fernflower.java:106)
        at org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler.addSource(ConsoleDecompiler.java:202)
        at org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler.main(ConsoleDecompiler.java:162)

**Comment by vipreshjha** [comment]
This happened as I was trying to Decompile an alread Decompiled file.
