### ISSUE TITLE
Method couldn't be decompiled - MergeHelper NullPointerException

### ISSUE THREAD

**Issue by zsrv** [QuiltMC/quiltflower#213]
Version: Quiltflower 1.9.0

The example() method in this class fails to decompile:

```java
import java.util.HashMap;
import java.util.Iterator;

public class MergeHelperNPE {
    private static HashMap hashMap = new HashMap();

    private static Iterator iterator() {
        return hashMap.values().iterator();
    }

    public static void example() {
        Iterator iter = iterator();
        while (iter.hasNext()) {
            MergeHelperNPE attr = (MergeHelperNPE) iter.next();
        }
    }
}
```

Error:

```
INFO:  Decompiling class MergeHelperNPE
INFO:     Loading Class: java/lang/Object from module java.base@11.0.15
WARN:           Method example ()V in class MergeHelperNPE couldn't be decompiled.
java.lang.NullPointerException
        at org.jetbrains.java.decompiler.modules.decompiler.MergeHelper.matchForEach(MergeHelper.java:645)
        at org.jetbrains.java.decompiler.modules.decompiler.MergeHelper.enhanceLoop(MergeHelper.java:50)
        at org.jetbrains.java.decompiler.modules.decompiler.MergeHelper.enhanceLoopsRec(MergeHelper.java:36)
        at org.jetbrains.java.decompiler.modules.decompiler.MergeHelper.enhanceLoopsRec(MergeHelper.java:31)
        at org.jetbrains.java.decompiler.modules.decompiler.MergeHelper.enhanceLoopsRec(MergeHelper.java:31)
        at org.jetbrains.java.decompiler.modules.decompiler.MergeHelper.enhanceLoops(MergeHelper.java:22)
        at org.jetbrains.java.decompiler.main.rels.MethodProcessor.codeToJava(MethodProcessor.java:240)
        at org.jetbrains.java.decompiler.main.rels.ClassWrapper.init(ClassWrapper.java:75)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.initWrappers(ClassesProcessor.java:543)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:454)
        at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:175)
        at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$2(ContextUnit.java:145)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Quiltflower output (MergeHelperNPE.java):

```java
import java.util.HashMap;
import java.util.Iterator;

public class MergeHelperNPE {
   private static HashMap hashMap = new HashMap();

   private static Iterator iterator() {
      return hashMap.values().iterator();
   }

   public static void example() {
      // $QF: Couldn't be decompiled
      // Please report this to the Quiltflower issue tracker, at https://github.com/QuiltMC/quiltflower/issues with a copy of the class file (if you have the rights to distribute it!)
      // java.lang.NullPointerException
      //   at org.jetbrains.java.decompiler.modules.decompiler.MergeHelper.matchForEach(MergeHelper.java:645)
      //   at org.jetbrains.java.decompiler.modules.decompiler.MergeHelper.enhanceLoop(MergeHelper.java:50)
      //   at org.jetbrains.java.decompiler.modules.decompiler.MergeHelper.enhanceLoopsRec(MergeHelper.java:36)
      //   at org.jetbrains.java.decompiler.modules.decompiler.MergeHelper.enhanceLoopsRec(MergeHelper.java:31)
      //   at org.jetbrains.java.decompiler.modules.decompiler.MergeHelper.enhanceLoopsRec(MergeHelper.java:31)
      //   at org.jetbrains.java.decompiler.modules.decompiler.MergeHelper.enhanceLoops(MergeHelper.java:22)
      //   at org.jetbrains.java.decompiler.main.rels.MethodProcessor.codeToJava(MethodProcessor.java:240)
      //
      // Bytecode:
      // 00: invokestatic MergeHelperNPE.iterator ()Ljava/util/Iterator;
      // 03: astore 0
      // 04: aload 0
      // 05: invokeinterface java/util/Iterator.hasNext ()Z 1
      // 0a: ifeq 1a
      // 0d: aload 0
      // 0e: invokeinterface java/util/Iterator.next ()Ljava/lang/Object; 1
      // 13: checkcast MergeHelperNPE
      // 16: astore 1
      // 17: goto 04
      // 1a: return
   }
}
```

**Comment by SuperCoder7979** [comment]
Should be fixed by 47bdeec823086e703fc6301b0b7dc7a88116412a. Thanks for the report!
