### ISSUE TITLE
Method couldn't be decompiled - invalid constant type Ljava/lang/Object

### ISSUE THREAD

**Issue by zsrv** [QuiltMC/quiltflower#214]
Version: Quiltflower 1.9.0

The example() method in this class fails to decompile:

```java
public class InvalidConstantTypeRE {
    public Object example(boolean bool) {
        Object value = "";

        if (bool) {
            value = null;
        }
        else {
            value = null;
        }

        return value;
    }
}
```

Error:

```
INFO:  Decompiling class InvalidConstantTypeRE
INFO:     Loading Class: java/lang/Object from module java.base@11.0.15
WARN:        Method example (Z)Ljava/lang/Object; in class InvalidConstantTypeRE couldn't be written.
java.lang.RuntimeException: invalid constant type: Ljava/lang/Object;
        at org.jetbrains.java.decompiler.modules.decompiler.exps.ConstExprent.toJava(ConstExprent.java:361)
        at org.jetbrains.java.decompiler.modules.decompiler.exps.AssignmentExprent.toJava(AssignmentExprent.java:131)
        at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.listToJava(ExprProcessor.java:967)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.BasicBlockStatement.toJava(BasicBlockStatement.java:65)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.IfStatement.toJava(IfStatement.java:202)
        at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.jmpWrapper(ExprProcessor.java:905)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.SequenceStatement.toJava(SequenceStatement.java:107)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.RootStatement.toJava(RootStatement.java:37)
        at org.jetbrains.java.decompiler.main.ClassWriter.methodToJava(ClassWriter.java:1172)
        at org.jetbrains.java.decompiler.main.ClassWriter.classToJava(ClassWriter.java:393)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:480)
        at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:175)
        at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$2(ContextUnit.java:145)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Quiltflower output (InvalidConstantTypeRE.java):

```java
public class InvalidConstantTypeRE {
   public Object example(boolean bool) {
      // $QF: Couldn't be decompiled
      // Please report this to the Quiltflower issue tracker, at https://github.com/QuiltMC/quiltflower/issues with a copy of the class file (if you have the rights to distribute it!)
      // java.lang.RuntimeException: invalid constant type: Ljava/lang/Object;
      //   at org.jetbrains.java.decompiler.modules.decompiler.exps.ConstExprent.toJava(ConstExprent.java:361)
      //   at org.jetbrains.java.decompiler.modules.decompiler.exps.AssignmentExprent.toJava(AssignmentExprent.java:131)
      //   at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.listToJava(ExprProcessor.java:967)
      //   at org.jetbrains.java.decompiler.modules.decompiler.stats.BasicBlockStatement.toJava(BasicBlockStatement.java:65)
      //   at org.jetbrains.java.decompiler.modules.decompiler.stats.IfStatement.toJava(IfStatement.java:202)
      //   at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.jmpWrapper(ExprProcessor.java:905)
      //   at org.jetbrains.java.decompiler.modules.decompiler.stats.SequenceStatement.toJava(SequenceStatement.java:107)
      //   at org.jetbrains.java.decompiler.modules.decompiler.stats.RootStatement.toJava(RootStatement.java:37)
      //   at org.jetbrains.java.decompiler.main.ClassWriter.methodToJava(ClassWriter.java:1172)
      //
      // Bytecode:
      // 0: ldc ""
      // 2: astore 2
      // 3: iload 1
      // 4: ifeq c
      // 7: aconst_null
      // 8: astore 2
      // 9: goto e
      // c: aconst_null
      // d: astore 2
      // e: aload 2
      // f: areturn
   }
}
```

**Comment by SuperCoder7979** [comment]
Should be fixed by aea5fd12. Thank you for the report!
