### ISSUE TITLE
Latest IJ plugin fails to download the quiltflower decompiler

### ISSUE THREAD

**Issue by sureshg** [QuiltMC/quiltflower#221]
#### Env

```bash
IntelliJ IDEA 2022.3 RC (Ultimate Edition)
Build #IU-223.7571.123, built on November 23, 2022
macOS 12.5
net.earthcomputer.quiltflowerintellij (1.0.4)
Kotlin: 223-1.7.20-release-201-IJ7571.123
```

Getting the following error

```
java.lang.Throwable: Failed to download quiltflower 1.8.1 from https://maven.quiltmc.org/repository/snapshot/org/quiltmc/quiltflower/1.8.1-SNAPSHOT/quiltflower-1.8.1.jar: 404
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at net.earthcomputer.quiltflowerintellij.QuiltflowerState$downloadQuiltflower$1$future$1$1.invoke(QuiltflowerState.kt:162)
	at net.earthcomputer.quiltflowerintellij.QuiltflowerState$downloadQuiltflower$1$future$1$1.invoke(QuiltflowerState.kt:122
)
```

**Comment by kb-1000** [comment]
The IntelliJ plugin is at https://github.com/Earthcomputer/quiltflower-intellij-plugin/, not in this repository

**Comment by Earthcomputer** [comment]
Have you tried restarting the IDE?

**Comment by sureshg** [comment]
@Earthcomputer disabled `autoupdate` and seems working fine after that. Thanks for the help. Will close this issue now.
