### ISSUE TITLE
Errors decompiling quiltflower itself.

### ISSUE THREAD

**Issue by msx80** [QuiltMC/quiltflower#97]
So i run the following with java 11: `java -jar quiltflower-1.8.1.jar quiltflower-1.8.1.jar outdec`
It produces an error in some classes, heres an example:

```
package org.jetbrains.java.decompiler.util;

import org.jetbrains.java.decompiler.struct.StructContext;

public class ClasspathScanner {
   public static void addAllClasspath(StructContext param0) {
      // $FF: Couldn't be decompiled
      // Please report this to the Quiltflower issue tracker, at https://github.com/QuiltMC/quiltflower/issues with a copy of the class file (if you have the rights to distribute it!)
      // java.lang.ClassCastException: class org.jetbrains.java.decompiler.struct.consts.LinkConstant cannot be cast to class org.jetbrains.java.decompiler.struct.consts.PrimitiveConstant (org.jetbrains.java.decompiler.struct.consts.LinkConstant and org.jetbrains.java.decompiler.struct.consts.PrimitiveConstant are in unnamed module of loader 'app')
      //   at org.jetbrains.java.decompiler.struct.consts.ConstantPool.getPrimitiveConstant(ConstantPool.java:138)
      //   at org.jetbrains.java.decompiler.code.interpreter.InstructionImpact.processSpecialInstructions(InstructionImpact.java:490)
      //   at org.jetbrains.java.decompiler.code.interpreter.InstructionImpact.stepTypes(InstructionImpact.java:363)
      //   at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.removeJsrInstructions(ControlFlowGraph.java:740)
      //   at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.removeJsrInstructions(ControlFlowGraph.java:762)
      //   at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.removeJsrInstructions(ControlFlowGraph.java:762)
      //   at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.removeJsrInstructions(ControlFlowGraph.java:762)
      //   at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.removeJsrInstructions(ControlFlowGraph.java:762)
      //   at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.removeJsrInstructions(ControlFlowGraph.java:762)
      //   at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.removeJsrInstructions(ControlFlowGraph.java:762)
      //   at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.removeJsrInstructions(ControlFlowGraph.java:762)
      //   at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.removeJsrInstructions(ControlFlowGraph.java:762)
      //   at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.removeJsr(ControlFlowGraph.java:724)
      //   at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.inlineJsr(ControlFlowGraph.java:107)
      //   at org.jetbrains.java.decompiler.main.rels.MethodProcessorRunnable.codeToJava(MethodProcessorRunnable.java:87)
      //
      // Bytecode:
      // 00: new java/util/HashSet
      // 03: dup
      // 04: invokespecial java/util/HashSet.<init> ()V
      // 07: astore 1
      // 08: bipush 2
      // 09: anewarray 4
      // 0c: dup
      // 0d: bipush 0
      // 0e: ldc "java.class.path"
      // 10: invokestatic java/lang/System.getProperty (Ljava/lang/String;)Ljava/lang/String;
      // 13: aastore
      // 14: dup
      // 15: bipush 1
      // 16: ldc "sun.boot.class.path"
      // 18: invokestatic java/lang/System.getProperty (Ljava/lang/String;)Ljava/lang/String;
      // 1b: aastore
      // 1c: astore 2
      // 1d: aload 2
      // 1e: astore 3
      // 1f: aload 3
      // 20: arraylength
      // 21: istore 4
      // 23: bipush 0
      // 24: istore 5
      // 26: iload 5
      // 28: iload 4
      // 2a: if_icmpge d5
      // 2d: aload 3
      // 2e: iload 5
      // 30: aaload
      // 31: astore 6
      // 33: aload 6
      // 35: ifnonnull 3b
      // 38: goto cf
      // 3b: aload 6
      // 3d: getstatic java/io/File.pathSeparator Ljava/lang/String;
      // 40: invokevirtual java/lang/String.split (Ljava/lang/String;)[Ljava/lang/String;
      // 43: astore 7
      // 45: aload 7
      // 47: arraylength
      // 48: istore 8
      // 4a: bipush 0
      // 4b: istore 9
      // 4d: iload 9
      // 4f: iload 8
      // 51: if_icmpge cf
      // 54: aload 7
      // 56: iload 9
      // 58: aaload
      // 59: astore 10
      // 5b: new java/io/File
      // 5e: dup
      // 5f: aload 10
      // 61: invokespecial java/io/File.<init> (Ljava/lang/String;)V
      // 64: astore 11
      // 66: aload 1
      // 67: aload 11
      // 69: invokevirtual java/io/File.getAbsolutePath ()Ljava/lang/String;
      // 6c: invokeinterface java/util/Set.contains (Ljava/lang/Object;)Z 2
      // 71: ifeq 77
      // 74: goto c9
      // 77: aload 11
      // 79: invokevirtual java/io/File.exists ()Z
      // 7c: ifeq c9
      // 7f: aload 11
      // 81: invokevirtual java/io/File.getName ()Ljava/lang/String;
      // 84: ldc ".class"
      // 86: invokevirtual java/lang/String.endsWith (Ljava/lang/String;)Z
      // 89: ifne 99
      // 8c: aload 11
      // 8e: invokevirtual java/io/File.getName ()Ljava/lang/String;
      // 91: ldc ".jar"
      // 93: invokevirtual java/lang/String.endsWith (Ljava/lang/String;)Z
      // 96: ifeq c9
      // 99: invokestatic org/jetbrains/java/decompiler/main/DecompilerContext.getLogger ()Lorg/jetbrains/java/decompiler/main/extern/IFernflowerLogger;
      // 9c: new null.makeConcatWithConstants (Ljava/io/File;)Ljava/lang/String;
      // 9f: dup
      // a0: invokespecial org/jetbrains/java/decompiler/main/extern/IFernflowerLogger$Severity.INFO Lorg/jetbrains/java/decompiler/main/extern/IFernflowerLogger$Severity;
      // a3: ldc org/jetbrains/java/decompiler/main/extern/IFernflowerLogger.writeMessage (Ljava/lang/String;Lorg/jetbrains/java/decompiler/main/extern/IFernflowerLogger$Severity;)V
      // a5: invokevirtual org/jetbrains/java/decompiler/struct/StructContext.addSpace (Ljava/io/File;Z)V
      // a8: aload 11
      // aa: invokevirtual java/util/Set.add (Ljava/lang/Object;)Z
      // ad: invokevirtual org/jetbrains/java/decompiler/util/ClasspathScanner.addAllModulePath (Lorg/jetbrains/java/decompiler/struct/StructContext;)V
      // b0: getstatic java/lang/module/ModuleFinder.ofSystem ()Ljava/lang/module/ModuleFinder;
      // b3: invokevirtual java/lang/module/ModuleFinder.findAll ()Ljava/util/Set;
      // b6: aload 0
      // b7: aload 11
      // b9: bipush 0
      // ba: invokevirtual java/util/Set.iterator ()Ljava/util/Iterator;
      // bd: aload 1
      // be: aload 11
      // c0: invokevirtual java/io/File.getAbsolutePath ()Ljava/lang/String;
      // c3: invokeinterface java/util/Iterator.hasNext ()Z 2
      // c8: pop
      // c9: iinc 9 1
      // cc: goto 4d
      // cf: iinc 5 1
      // d2: goto 26
      // d5: return
   }
}
```

**Comment by skyrising** [comment]
Fixed by f2b8f9f7bbe66db8dd1f4718d818110a3bba3bf2
